### ISSUE TITLE
Comments at the end of lines aren't recognized.

### ISSUE THREAD

**Issue by obskyr** [Bananattack/rgbds_textmate#1]
Comments that appear after other text on a line don't get highlit. Try:

```text
; This gets highlit...
DB $00   ; ...but no highlight here.
ld a, b  ; Not here either.
jp start ; Or here. :(
```

And it'll look a bit like the following:

![Tough luck.](https://user-images.githubusercontent.com/4363779/30712225-975724e0-9f0b-11e7-9761-28cb9b576f4d.png)

**Comment by Bananattack** [comment]
Hmm, it works for me here? I'm not sure what's causing it to not work in those cases. Maybe this is a program version difference? I'm still using Sublime Text Version 2.0.2, Build 2221 here. 

![image](https://user-images.githubusercontent.com/95647/30776441-7725ede0-a074-11e7-911a-d8aa59f8103e.png)

I double-checked removing the indentation at the start of a line to see if it makes a difference, but it seems fine here. The regex for comments is set to go from the marker until end-of-line... Is it possible the highlighter is getting stuck in one of the other rules? I noticed in your screenshot, there's no formatting on the operands either, it seems to stop formatting after the directive / mnemonic keywords. But hard to say if that's unusual without knowing how your color scheme looks on other code.

I'm not really sure what's going on here. That said, if you find a fix for it that works, I'll be happy to merge it in!
