### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tobiasvl** [Bananattack/rgbds_textmate#2]
Hey! I don't want to be impertinent, but would you consider licensing this under a permissive license? I'd very much like to convert it to an Atom package.

If you don't want to copyleft this repo, would you consider converting it to Atom yourself?

**Comment by tobiasvl** [comment]
It turned out that you can convert TextMate language bundles (`tmBundle`) automatically to Atom packages, but not `tmLanguage` files like yours, so it would require some work to convert it anyway.

So I wrote my own from scratch instead: https://atom.io/packages/language-rgbasm

It was inspired by yours, but not actually based on your code (although since Atom basically uses TextMate languages, including scope selector naming conventions, it's not completely different either).

**Comment by tobiasvl** [comment]
Actually I'll reopen this even though I don't personally need a license any more, because it'd be nice if this had a permissive license :)

**Comment by Bananattack** [comment]
Oh, sorry this never notified me. Whoops I should have put an explicit license for this repo. But anyways, feel free to use this for whatever purpose. I hereby release this repository under the public domain. I'll put a license file up to call that out.
